import { Avatar } from '@chakra-ui/avatar'
import { Button } from '@chakra-ui/button'
import { Box, Container, Divider, Heading, SimpleGrid } from '@chakra-ui/layout'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'


const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/web.jpg" />
      </Head>
      <header>
        <Box bgColor="#ffd100" p={5}>
          <Container maxW={1280} >
            <Avatar name="Felix Koch" src="/web.jpg"  />
          </Container>
        </Box>
      </header>

      <main style={{ height: "100vh" }}>
        <Box bgColor="#ffd100" p={5}>
          <Container maxW={1280}>
            <Heading as="h1" size="4xl">
              Felix Koch
            </Heading>
            <Box borderTop={10} borderColor="gray.800" borderStyle="solid" width="xs" mt={10} mb={10}></Box>
            <Heading as="h1" size="2xl" mb={20}>
              Founder<br />Freelance Full Stack Developer<br />Freelance Data Analyst<br />Father & Beekeeper
            </Heading>
            <SimpleGrid columns={4} mb={10}>
              <Box>
                <Button variant="outline" size="lg" borderColor="gray.800" borderWidth="3px">
                  felix@tagungshotels.info
                </Button>
              </Box>
              <Box>
                <Button variant="outline" size="lg" borderColor="gray.800" borderWidth="3px">
                  +49 4266 999 999 9
                </Button>
              </Box>
              <Box>
                <Button variant="outline" size="lg" borderColor="gray.800" borderWidth="3px">
                  Make an appointment
                </Button>
              </Box>
            </SimpleGrid>
          </Container>
        </Box>

        <Container maxW={1280} >
          body
        </Container>


      </main>

      <footer>
        <Box bgColor="#d6d6d6" p={10}>
          <Container maxW={1280} >
            footer
          </Container>
        </Box>
      </footer>
    </div>
  )
}

export default Home
