import { Avatar } from '@chakra-ui/avatar'
import { Button } from '@chakra-ui/button'
import { Box, Container, Divider, Heading, List, ListIcon, ListItem, SimpleGrid, Text, Wrap, WrapItem } from '@chakra-ui/layout'
import type { NextPage } from 'next'
import Head from 'next/head'
import { PhoneIcon, EmailIcon, CalendarIcon } from '@chakra-ui/icons'
import {AiFillLinkedin} from "react-icons/ai"
import {FaLinkedin} from "react-icons/fa"
const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/web.jpg" />
      </Head>
      <header>
        <Box bgColor="#ffd100" p={5}>
          <Container maxW={1280} >
            <Avatar name="Felix Koch" src="/web.jpg" />
          </Container>
        </Box>
      </header>

      <main style={{ height: "100vh" }}>
        <Box bgColor="#ffd100" p={5}>
          <Container maxW={1280}>
            <Heading as="h1" size="4xl">
              Felix Koch
            </Heading>
            <Box borderTop={10} borderColor="gray.800" borderStyle="solid" width="xs" mt={10} mb={10}></Box>
            <Heading as="h1" size="2xl" mb={16}>
              Founder<br />Freelance Full Stack Developer<br />Freelance Data Analyst<br />Father & Beekeeper
            </Heading>

            <Text fontSize='2xl' mb={5}>Please get in touch</Text>

            <Wrap spacing="30px" mb={10}>
              <WrapItem>
                <Button leftIcon={<EmailIcon />} variant="outline" size="lg" borderColor="gray.800" borderWidth="3px">
                  felix@tagungshotels.info
                </Button>
              </WrapItem>
              <WrapItem>
                <Button leftIcon={<PhoneIcon />} variant="outline" size="lg" borderColor="gray.800" borderWidth="3px">
                  +49 4266 999 999 9
                </Button>
              </WrapItem>
              <WrapItem>
                <Button leftIcon={<CalendarIcon />} variant="outline" size="lg" borderColor="gray.800" borderWidth="3px">
                  Make an appointment
                </Button>
              </WrapItem>
            </Wrap>
          </Container>
        </Box>

        <Container maxW={1280} >
          body
        </Container>


      </main>

      <footer>
        <Box bgColor="#d6d6d6" p={10}>
          <Container maxW={1280} >
            <SimpleGrid columns={2}>
              <Box>
                <List spacing={3}>
                  <ListItem fontSize="xl">

                    <a href='#'>
                      Imprint
                    </a>
                  </ListItem>
                  <ListItem fontSize="xl">
                    Privacy
                  </ListItem>
                </List>
              </Box>
              <Box>
                <List spacing={3}>
                  <ListItem fontSize="xl">

                    <ListIcon as={AiFillLinkedin} />
                    <a href='#'>
                      LinkedIn
                    </a>
                  </ListItem>
                  <ListItem fontSize="xl">
                    <ListIcon as={FaLinkedin} fontSize="2xl"/>
                    Github
                  </ListItem>
                </List>

              </Box>
            </SimpleGrid>
          </Container>
        </Box>
      </footer>
    </div>
  )
}

export default Home
